on:
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
    pull_request:
        branches:
            - main
            - "release/**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5.0.0
            
            - name: Run Test
              run: npm test
